AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda Functions for Agentic Architectures'

Resources:
  AgentFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: agentic-agent-function
      Runtime: python3.10
      Handler: index.handler
      Role: !GetAtt AgentExecutionRole.Arn
      Code:
        ZipFile: |
          def handler(event, context):
              return {"statusCode": 200, "body": "Agent executed"}
      Environment:
        Variables:
          REGION: us-east-1

  AgentExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
